**Индексация и выбор данных из массивов NumPy**

In [1]:
import numpy as np

In [11]:
arr = np.arange(0, 11)

In [4]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [5]:
arr[8]

np.int64(8)

In [6]:
arr[1:5]

array([1, 2, 3, 4])

In [7]:
arr[:5]

array([0, 1, 2, 3, 4])

In [8]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [13]:
arr[0:5] = 100

In [14]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [16]:
arr = np.arange(0, 11)

In [17]:
slice_of_array = arr[0:5]

In [18]:
slice_of_array

array([0, 1, 2, 3, 4])

In [19]:
slice_of_array[:] = 99

In [20]:
slice_of_array

array([99, 99, 99, 99, 99])

In [21]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [22]:
arr_copy = arr.copy()

In [23]:
arr_copy[:] = 100

In [26]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [27]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [28]:
arr_2d = np.array([[5, 10, 15], [20, 25, 30], [35, 40, 45]])

In [29]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [30]:
arr_2d.shape

(3, 3)

In [31]:
arr_2d[0]

array([ 5, 10, 15])

In [33]:
arr_2d[2][0]

np.int64(35)

In [35]:
arr_2d[1, 2]

np.int64(30)

In [37]:
arr_2d[:2, 1:]

array([[10, 15],
       [25, 30]])

In [38]:
arr = np.arange(0, 11)

In [39]:
arr > 4

array([False, False, False, False, False,  True,  True,  True,  True,
        True,  True])

In [40]:
bool_array = arr > 4

In [41]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[bool_array]

array([ 5,  6,  7,  8,  9, 10])