<a href="https://colab.research.google.com/github/wuxianaisai/big_ml_course/blob/main/numpy_arrays_0.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Массивы NumPy**

In [27]:
import numpy as np

In [28]:
my_list = [1, 2, 3]

In [29]:
type(my_list)

list

In [30]:
np.array(my_list)

array([1, 2, 3])

In [31]:
myarr = np.array(my_list)

In [32]:
myarr

array([1, 2, 3])

In [33]:
type(myarr)

numpy.ndarray

In [34]:
my_matrix = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [35]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
np.arange(0, 101, 20)

array([  0,  20,  40,  60,  80, 100])

In [37]:
np.zeros(3)

array([0., 0., 0.])

In [38]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [39]:
np.ones((6, 6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [40]:
np.linspace(0, 15, 6)

array([ 0.,  3.,  6.,  9., 12., 15.])

In [41]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [42]:
np.random.rand(3, 5)

array([[0.25541191, 0.59433065, 0.70596633, 0.45067743, 0.77789548],
       [0.77125049, 0.45048596, 0.86726665, 0.90560029, 0.40342732],
       [0.40514489, 0.76581155, 0.19541396, 0.03818818, 0.05818185]])

In [43]:
np.random.randn(10)

array([ 0.5062566 , -0.51435053,  0.29823777, -0.16067147,  1.21324158,
       -0.6934248 ,  0.70235097, -0.40694358,  1.06207926,  0.53942692])

In [44]:
np.random.randint(80, 100, 2)

array([88, 99])

In [45]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [46]:
arr = np.arange(0, 30)

In [47]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29])

In [48]:
arr = arr.reshape(5,6)

In [49]:
ranarr = np.random.randint(0,101,10)

In [50]:
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [51]:
ranarr.max()

np.int64(99)

In [52]:
ranarr.min()

np.int64(2)

In [53]:
ranarr.argmax()

np.int64(5)

In [54]:
ranarr.argmin()

np.int64(7)

In [55]:
ranarr.dtype

dtype('int64')

In [56]:
arr.shape

(5, 6)