**Операции в NumPy**

In [1]:
import numpy as np

In [44]:
arr = np.arange(0, 10)

In [45]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [46]:
arr + 5

array([ 5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [47]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
arr - 2

array([-2, -1,  0,  1,  2,  3,  4,  5,  6,  7])

In [49]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [50]:
arr * arr

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

In [51]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [52]:
arr / arr

<ipython-input-52-7f952cd3e0ce>:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [53]:
1 / arr

<ipython-input-53-e66ae8057bc3>:1: RuntimeWarning: divide by zero encountered in divide
  1 / arr


array([       inf, 1.        , 0.5       , 0.33333333, 0.25      ,
       0.2       , 0.16666667, 0.14285714, 0.125     , 0.11111111])

In [55]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [56]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849])

In [57]:
np.log(arr)

<ipython-input-57-a67b4ae04e95>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

In [58]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
arr.sum()

np.int64(45)

In [60]:
arr.mean()

np.float64(4.5)

In [61]:
arr.max()

np.int64(9)

In [62]:
arr.var()

np.float64(8.25)

In [63]:
arr.std()

np.float64(2.8722813232690143)

In [64]:
arr_2d = np.arange(0, 25).reshape(5, 5)

In [65]:
arr_2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [66]:
arr_2d.sum()

np.int64(300)

In [68]:
arr_2d.sum(axis=0) # сумма колонок

array([50, 55, 60, 65, 70])

In [69]:
arr_2d.sum(axis=1) # сумма строк

array([ 10,  35,  60,  85, 110])